name: Build and release container directly from master

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"
      - LICENCE
      - TRANSLATION
      - invidious.service
      - .git*
      - .editorconfig
      - screenshots/*
      - .github/ISSUE_TEMPLATE/*
      - kubernetes/**

jobs:
  release:
    strategy:
      matrix:
        include:
          # AMD64 - Standard
          - os: ubuntu-latest
            platform: linux/amd64
            name: "AMD64"
            dockerfile: "docker/Dockerfile"
            tag_suffix: ""
            api_only: "0"
          # AMD64 - API Only
          - os: ubuntu-latest
            platform: linux/amd64
            name: "AMD64 API-Only"
            dockerfile: "docker/Dockerfile"
            tag_suffix: "-api-only"
            api_only: "1"
          # ARM64 - Standard
          - os: ubuntu-24.04-arm
            platform: linux/arm64/v8
            name: "ARM64"
            dockerfile: "docker/Dockerfile.arm64"
            tag_suffix: "-arm64"
            api_only: "0"
          # ARM64 - API Only
          - os: ubuntu-24.04-arm
            platform: linux/arm64/v8
            name: "ARM64 API-Only"
            dockerfile: "docker/Dockerfile.arm64"
            tag_suffix: "-arm64-api-only"
            api_only: "1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            suffix=${{ matrix.tag_suffix }}
          tags: |
            type=sha,format=short,prefix={{date 'YYYY.MM.DD'}}-,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=master,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          labels: |
            quay.expires-after=12w

      - name: Build and push Docker ${{ matrix.name }} image for Push Event
        uses: docker/build-push-action@v6
        with:
          context: .
          file:  ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            "release=1"
            "api_only=${{ matrix.api_only }}"
